### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(DDrumContent)
add_subdirectory(DDrum)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "Sounds/Blow.wav"
        "Sounds/Synth.wav"
        "Sounds/Roll.wav"
        "Sounds/WhistleMonoS32.wav"
        "Sounds/WhistleStereoS32.wav"
        "Sounds/Whistle.wav"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    DDrumContentplugin
    DDrumplugin)