# This file is automatically generated by Qt Design Studio.
from pathlib import Path

project_root = Path(__file__).parent.parent.parent

if '__compiled__' in globals():
    qml_app_url = ":/qt/qml/DDrumContent/App.qml"
else:
    qml_app_url = "DDrumContent/App.qml"